// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testLocalizations(t *testing.T) {
	t.Parallel()

	query := Localizations()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testLocalizationsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLocalizationsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Localizations().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLocalizationsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LocalizationSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLocalizationsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := LocalizationExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Localization exists: %s", err)
	}
	if !e {
		t.Errorf("Expected LocalizationExists to return true, but got false.")
	}
}

func testLocalizationsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	localizationFound, err := FindLocalization(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if localizationFound == nil {
		t.Error("want a record, got nil")
	}
}

func testLocalizationsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Localizations().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testLocalizationsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Localizations().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testLocalizationsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	localizationOne := &Localization{}
	localizationTwo := &Localization{}
	if err = randomize.Struct(seed, localizationOne, localizationDBTypes, false, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}
	if err = randomize.Struct(seed, localizationTwo, localizationDBTypes, false, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = localizationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = localizationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Localizations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testLocalizationsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	localizationOne := &Localization{}
	localizationTwo := &Localization{}
	if err = randomize.Struct(seed, localizationOne, localizationDBTypes, false, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}
	if err = randomize.Struct(seed, localizationTwo, localizationDBTypes, false, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = localizationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = localizationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func localizationBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Localization) error {
	*o = Localization{}
	return nil
}

func localizationAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Localization) error {
	*o = Localization{}
	return nil
}

func localizationAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Localization) error {
	*o = Localization{}
	return nil
}

func localizationBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Localization) error {
	*o = Localization{}
	return nil
}

func localizationAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Localization) error {
	*o = Localization{}
	return nil
}

func localizationBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Localization) error {
	*o = Localization{}
	return nil
}

func localizationAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Localization) error {
	*o = Localization{}
	return nil
}

func localizationBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Localization) error {
	*o = Localization{}
	return nil
}

func localizationAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Localization) error {
	*o = Localization{}
	return nil
}

func testLocalizationsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Localization{}
	o := &Localization{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, localizationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Localization object: %s", err)
	}

	AddLocalizationHook(boil.BeforeInsertHook, localizationBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	localizationBeforeInsertHooks = []LocalizationHook{}

	AddLocalizationHook(boil.AfterInsertHook, localizationAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	localizationAfterInsertHooks = []LocalizationHook{}

	AddLocalizationHook(boil.AfterSelectHook, localizationAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	localizationAfterSelectHooks = []LocalizationHook{}

	AddLocalizationHook(boil.BeforeUpdateHook, localizationBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	localizationBeforeUpdateHooks = []LocalizationHook{}

	AddLocalizationHook(boil.AfterUpdateHook, localizationAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	localizationAfterUpdateHooks = []LocalizationHook{}

	AddLocalizationHook(boil.BeforeDeleteHook, localizationBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	localizationBeforeDeleteHooks = []LocalizationHook{}

	AddLocalizationHook(boil.AfterDeleteHook, localizationAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	localizationAfterDeleteHooks = []LocalizationHook{}

	AddLocalizationHook(boil.BeforeUpsertHook, localizationBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	localizationBeforeUpsertHooks = []LocalizationHook{}

	AddLocalizationHook(boil.AfterUpsertHook, localizationAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	localizationAfterUpsertHooks = []LocalizationHook{}
}

func testLocalizationsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLocalizationsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(localizationColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLocalizationsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLocalizationsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LocalizationSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLocalizationsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Localizations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	localizationDBTypes = map[string]string{`ID`: `int`, `Longitude`: `double`, `Latitude`: `double`}
	_                   = bytes.MinRead
)

func testLocalizationsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(localizationPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(localizationAllColumns) == len(localizationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testLocalizationsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(localizationAllColumns) == len(localizationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Localization{}
	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, localizationDBTypes, true, localizationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(localizationAllColumns, localizationPrimaryKeyColumns) {
		fields = localizationAllColumns
	} else {
		fields = strmangle.SetComplement(
			localizationAllColumns,
			localizationPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := LocalizationSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testLocalizationsUpsert(t *testing.T) {
	t.Parallel()

	if len(localizationAllColumns) == len(localizationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLLocalizationUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Localization{}
	if err = randomize.Struct(seed, &o, localizationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Localization: %s", err)
	}

	count, err := Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, localizationDBTypes, false, localizationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Localization struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Localization: %s", err)
	}

	count, err = Localizations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
